#
# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
admin_lte:
    options:
        # default image for missing user avatar images
        default_avatar: bundles/adminlte/images/default_avatar.png
        # default image for missing logos
        default_brand_logo: bundles/adminlte/images/adminltelogo.png
        # the color skin
        skin: skin-blue
        # fixes the position of the header menu
        fixed_header: false
        # fixes the position of the left sidebar
        fixed_menu: false
        # fixes the position of the footer
        fixed_footer: false
        # boxed layout (true) or full-screen (false)
        boxed_layout: false
        # initial collapsed state of the sidebar
        collapsed_sidebar: false
        # whether the left menu/sidebar is shown when minified or completely removed
        mini_sidebar: true
        # max number of notifications displayed
        max_navbar_notifications: 10
        # max number of tasks displayed
        max_navbar_tasks: 10
        # max number of messages displayed
        max_navbar_messages: 10

    # configurable tabs in the control_sidebar (right screen), see:
    # https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md
    # control_sidebar:
    #    home:
    #        icon: fas fa-home
    #        template: control-sidebar/home.html.twig
    #    settings:
    #        icon: fas fa-cogs
    #        controller: 'App\Controller\DefaultController::controlSidebarSettings'


    theme:
        widget:
            type: 'primary'
            collapsible: false
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
        button:
            type: 'primary'
            size: false

    knp_menu:
        enable: false
        main_menu: adminlte_main
        breadcrumb_menu: false

    routes:
        adminlte_welcome: home
        adminlte_login: login
        adminlte_login_check: login_check
        #adminlte_registration: registration
        #adminlte_password_reset: password_reset
        adminlte_message: message
        adminlte_messages: messages
        adminlte_notification: notification
        adminlte_notifications: notifications
        adminlte_task: task
        adminlte_tasks: tasks
        adminlte_profile: profile
