name: CI
on:
    pull_request: null
    push:
        branches:
            - master
jobs:
    coding-guidelines:
        name: Coding Guidelines

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.3
                  coverage: none

            - name: Install php dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

            - name: Run friendsofphp/php-cs-fixer
              run: vendor/bin/php-cs-fixer fix --diff-format=udiff --dry-run --show-progress=dots --using-cache=no --verbose

    static-code-analysis:
        name: Static Code Analysis

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.3
                  extensions: mbstring, xml, ctype, iconv, intl
                  coverage: none
                  ini-values: memory_limit=-1

            - name: Install php dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

            - name: Run phpstan/phpstan
              run: composer phpstan

    tests:
        name: Tests

        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.1', '7.2', '7.3', '7.4' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                coverage: none
                extensions: mbstring, xml, ctype, iconv, intl

            - name: Install php dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

            - name: Run tests with phpunit
              run: composer tests
